# Best hyperparameters for LSTM with padding manual padding cutting

import: [lstm_lookup_embedder]

# settings for the dataset to use
dataset:
  type: olp
  name: olpbench

# settings for ComplEx and the respective embedders
model: complex

complex:
  entity_embedder.type: lstm_lookup_embedder
  relation_embedder.type: lstm_lookup_embedder

lstm_lookup_embedder:
  initialize: xavier_uniform_ # is Glorot initialization
  bin_within_batch: False
  bin_size: 50
  dim: 512
  dropout: 0.07593923183158041

# settings for the training job of each hyperparameter combination
train:
  type: negative_sampling
  max_epochs: 100
  batch_size: 4096
  subbatch_auto_tune: True
  optimizer:
    +++: +++
    default:
      type: Adagrad
      args:
        +++: +++
        lr: 0.055758330747485166
        weight_decay: 7.179384912855923e-07

# settings for negative sampling
negative_sampling:
  shared: True
  with_replacement: False
  implementation: batch
  samples_within_batch: True

# settings for the evaluation job
eval:
  type: olp_entity_ranking
  batch_size: 500
