import: [packed_lstm_lookup_embedder]                                         #!!! adjust if model is changed

# settings for the dataset to use
dataset:
  type: olp
  name: olpbench
  byte_pair_encoding: False

# settings for ComplEx and the respective embedders
model: complex

complex:
  entity_embedder.type: packed_lstm_lookup_embedder                           #!!! adjust if model is changed
  relation_embedder.type: packed_lstm_lookup_embedder                         #!!! adjust if model is changed

packed_lstm_lookup_embedder:                                                  #!!! adjust if model is changed (incl. parameters of the model)
  initialize: xavier_uniform_ # is Glorot initialization
  dropout: 0.07800686648115517
  pretrained:
    use: True
    file:
      name: enwiki_20180420_500d  #glove.840B.300d_word2vec
      type: txt
    oov_tactic: 'random'
    freeze: False
    use_pickle: True

# settings for the training job of each hyperparameter combination
train:
  type: negative_sampling
  max_epochs: 100
  batch_size: 4096
  subbatch_auto_tune: True
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.16071061396040023
        weight_decay: 5.501112763443961e-07
      type: Adagrad


negative_sampling:
  shared: True
  with_replacement: False
  implementation: batch
  samples_within_batch: True

# settings for the evaluation job
eval:
  type: olp_entity_ranking
  batch_size: 500
