# Hyperparameter search for LSTM with PyTorch padding cutting and byte-pair encoding

import: [packed_lstm_lookup_embedder]

# general settings for the hyperparameter optimization job
job.type: search
search.type: manual
valid.metric: mean_reciprocal_rank_filtered
manual_search.configurations:
  - { folder: 'ent_1000_rel_1150', dataset.iterations_entities: 1000, dataset.iterations_relations: 1150 }
  - { folder: 'ent_2000_rel_1500', dataset.iterations_entities: 2000, dataset.iterations_relations: 1500 }
  - { folder: 'ent_5000_rel_2000', dataset.iterations_entities: 5000, dataset.iterations_relations: 2000 }
  - { folder: 'ent_12000_rel_3000', dataset.iterations_entities: 12000, dataset.iterations_relations: 3000 }
  - { folder: 'ent_17000_rel_5000', dataset.iterations_entities: 17000, dataset.iterations_relations: 5000 }
  - { folder: 'ent_55000_rel_8000', dataset.iterations_entities: 55000, dataset.iterations_relations: 8000 }
  - { folder: 'ent_78000_rel_17000', dataset.iterations_entities: 78000, dataset.iterations_relations: 17000 }
  - { folder: 'ent_160000_rel_31000', dataset.iterations_entities: 160000, dataset.iterations_relations: 31000 }
  - { folder: 'ent_209000_rel_43000', dataset.iterations_entities: 209000, dataset.iterations_relations: 43000 }
  - { folder: 'ent_230000_rel_50000', dataset.iterations_entities: 230000, dataset.iterations_relations: 50000 }


# settings for the dataset to use
dataset:
  type: olp
  name: olpbench
  byte_pair_encoding: True

# settings for ComplEx and the respective embedders
model: complex

complex:
  entity_embedder.type: packed_lstm_lookup_embedder
  relation_embedder.type: packed_lstm_lookup_embedder

packed_lstm_lookup_embedder:
  initialize: xavier_uniform_ # is Glorot initialization
  bin_within_batch: False
  bin_size: 50
  dim: 512
  dropout: 0.07593923183158041

# settings for the training job of each hyperparameter combination
train:
  type: negative_sampling
  max_epochs: 10
  batch_size: 4096
  subbatch_auto_tune: True
  optimizer:
    +++: +++
    default:
      type: Adagrad
      args:
        +++: +++
        lr: 0.055758330747485166
        weight_decay: 7.179384912855923e-07


# settings for negative sampling
negative_sampling:
  shared: True
  with_replacement: False
  implementation: batch
  samples_within_batch: True

# settings for the evaluation job
eval:
  type: olp_entity_ranking
  batch_size: 500
