job.type: train
dataset.name: olpbench

train:
  type: negative_sampling
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4
  batch_size: 4096
  subbatch_auto_tune: True

negative_sampling:
  implementation: batch

model: complex
unigram_pooling_embedder:
  dim: 100
  regularize_weight: 0.8e-7
      mean: 0.0
      std: 0.1


eval:
  type: olp_entity_ranking
  batch_size: 500

valid:
  every: 1

entity_ranking:
  chunk_size: -1